name: Push Source Files to Applanga
on:
  push:
    branches:
      - master
    paths:
      - www/_BASE.xliff
      - www/android_xml.xml
      - www/angular_translate_json.json
      - www/chrome_i18n_json.json
      - www/csv.csv
      - www/ember_i18n_json_module.js
      - www/i18n/en.csv
      - translations/app/en.json
      - www/en.xlsx
      - www/flutter_arb.arb
      - www/gettext_po.po
      - www/gettext_pot.pot
      - www/go_i18n_json.json
      - www/i18next_json.json
      - www/ini.ini
      - www/ios_strings.strings
      - www/ios_stringsdict.stringsdict
      - www/java_properties.properties
      - www/laravel_php.php
      - www/i18n/locale-en.json
      - www/mozilla_i18n_json.json
      - www/mozilla_properties.properties
      - www/nested_json.json
      - www/node_2_json.json
      - www/qt_ts.ts
      - www/react_nested_json.json
      - www/react_simple_json.json
      - www/ruby_on_rails_yaml.yaml
      - www/symfony_yaml.yaml
      - www/symfony2_yaml.yaml
  workflow_dispatch:
    inputs:
      push_targets:
        type: boolean
        description: Push translation files. If set translation files will be pushed instead of source files
        default: false
        required: false
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: checkout
      - uses: applanga/setup-applanga-cli@v1.0.3
        with:
          version: 1.0.*
      - name: Push Sources to Applanga
        if: '${{ inputs.push_targets != true }}'
        env:
          APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        run: applanga push --force
        working-directory: checkout
      - name: Push Translation Files to Applanga
        if: '${{ inputs.push_targets == true }}'
        env:
          APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
        run: applanga pushtarget --force
        working-directory: checkout
