name: "Pull Target Files from Applanga"
on:
  #schedule:
   #  * is a special character in YAML so you have to quote this string
   # - cron:  '*/10 * * * *'
   push:
    branches:
       - master
jobs:
  pull-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.0
        with:
          version: 1.0.48
      - run: applanga pull
        env:
          APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        working-directory: checkout
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: newTranslations
          commit-message: Updated translations
          title: Updated translations 
          body: Pulled in new translations from Applanga portal
          path: 'checkout'
