name: "TestAction"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: annakleszczynska/TestAction
      with:
        version: 1.0.45

    - run: npm ci
    - run: applanga push
