name: "TestAction"
on:
  push:
    branches:
      - master
jobs:
  trying-my-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: winify-ag/setup-phraseapp@v1
      with:
        version: 1.16.0
    - run: npm ci

